In [ ]:
print('Tensors')

Tensors


In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a tensor

In [ ]:
#using empty
a=torch.empty(2,3)
print(a) #phle se padi hui memory dikha dega


tensor([[-2.5571e-11,  4.4623e-41, -2.5571e-11],
        [ 4.4623e-41,  4.7393e+30,  4.7423e+30]])


In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
#using zeros

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand

torch.rand(2,3)

tensor([[0.6687, 0.7401, 0.7636],
        [0.8035, 0.6699, 0.5609]])

In [ ]:
#manual seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[552481648, 552453824,         0],
        [        0,         1,         0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

#Tensor Data Types

In [ ]:
#find data type


x.dtype

torch.int64

In [ ]:
#assign data type
torch.tensor([1.0,2.0,3.6],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#using to

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical operations


### 1.Scaler operation

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [ ]:
x*3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [ ]:
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [ ]:
#int division
(x*100)//3

tensor([[23., 26.],
        [13., 30.]])

In [ ]:
#mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [ ]:
#power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2.Element wise operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
#add
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [ ]:
#sub
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [ ]:
#multiply
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [ ]:
#divide
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [ ]:
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [ ]:
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
#abs

torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
#round

torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction opertaion



In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [ ]:
#sum
torch.sum(e)

tensor(24.)

In [ ]:
#sum along columns
torch.sum(e,dim=0)

tensor([ 8.,  0., 16.])

In [ ]:
#sum along rows
torch.sum(e,dim=1)

tensor([15.,  9.])

In [ ]:
#mean
torch.mean(e)

tensor(4.)

In [ ]:
#mean along col
torch.mean(e,dim=0)

tensor([4., 0., 8.])

In [ ]:
#median
torch.median(e)

tensor(0.)

In [ ]:
#max and min
torch.max(e)


tensor(9.)

In [ ]:
torch.min(e)

tensor(0.)

In [ ]:
#product
torch.prod(e)

tensor(0.)

In [ ]:
#standard deviation
torch.std(e)

tensor(4.4272)

In [ ]:
#variance
torch.var(e)

tensor(19.6000)

In [ ]:
#argmax
torch.argmax(e)

tensor(5)

In [ ]:
#argmin
torch.argmin(e) #provide index of min element

tensor(1)

### 4.Matrix Operation

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
g=torch.randint(size=(3,2),low=0,high=10,dtype=torch.float32)

print(f)
print(g)

tensor([[5., 7., 3.],
        [9., 4., 0.]])
tensor([[5., 7.],
        [5., 9.],
        [9., 7.]])


In [ ]:
#matrix multiplictaion
torch.matmul(f,g)

tensor([[ 87., 119.],
        [ 65.,  99.]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
#transpose
print(torch.transpose(f, 0, 1))

tensor([[5., 9.],
        [7., 4.],
        [3., 0.]])


In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [ ]:
#determinant
torch.det(h)

tensor(-110.)

In [ ]:
#inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5.Comparison Operation

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [ ]:
#greater than
i>j

tensor([[ True,  True, False],
        [ True, False, False]])

In [ ]:
i<j

tensor([[False, False,  True],
        [False,  True,  True]])

In [ ]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
i!=j

tensor([[True, True, True],
        [True, True, True]])

### 6. Special Function

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [ ]:
#log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [ ]:
#exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [ ]:
#sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [ ]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [ ]:
#softmax
torch.softmax(k,dim=0) #dim=0 means apply softmax on the whole vector


tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [ ]:
#relu.
torch.relu(k)


tensor([[3., 3., 5.],
        [0., 6., 4.]])

### Inplace Operation

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [ ]:
m.add_(n) #m me n add ho gaya

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [ ]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [ ]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [ ]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [ ]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [ ]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

### Copying a tensor

In [ ]:
a=torch.rand(2,3)

In [ ]:
b=a

In [ ]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
a[0][0]=0

In [ ]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
id(a)

136765939134016

In [ ]:
id(b)

136765939134016

In [ ]:
b=a.clone()

In [ ]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
a[0][0]=10

In [ ]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [ ]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [ ]:
id(a)

136765939134016

In [ ]:
id(b)

136765938530528

# Tensor operations on GPU

In [113]:
torch.cuda.is_available()

True

In [114]:
#storing Gpu device
device=torch.device('cuda')

In [115]:
#creating a new tensor on GPU
# until now we have make tensor on Cpu now we will use gpu ram

torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [116]:
#moving an existing tensor to GPU

a=torch.rand(2,3)

In [118]:
b=a.to(device)

In [119]:
b+5

tensor([[5.2243, 5.8935, 5.0497],
        [5.1780, 5.3011, 5.1893]], device='cuda:0')

In [120]:
import torch
import time

size = 10000

# -------------------
# Create matrices on CPU
# -------------------
a = torch.randn(size, size)
b = torch.randn(size, size)

# -------------------
# CPU time
# -------------------
start_cpu = time.time()

c_cpu = torch.matmul(a, b)

end_cpu = time.time()

print("CPU Time:", end_cpu - start_cpu, "seconds")

# -------------------
# Move to GPU
# -------------------
a = a.to(device)
b = b.to(device)

# warm-up (important for accurate timing)
torch.matmul(a, b)

# -------------------
# GPU time
# -------------------
start_gpu = time.time()

c_gpu = torch.matmul(a, b)

torch.cuda.synchronize()  # wait for GPU to finish

end_gpu = time.time()

print("GPU Time:", end_gpu - start_gpu, "seconds")

CPU Time: 16.119314670562744 seconds
GPU Time: 1.1401782035827637 seconds


### reshaping tensors

In [122]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [123]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [124]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [126]:
b=torch.rand(2,3,4)
b

tensor([[[0.2861, 0.7459, 0.8487, 0.4059],
         [0.2883, 0.2220, 0.6423, 0.7098],
         [0.5644, 0.4549, 0.0729, 0.8535]],

        [[0.9793, 0.0611, 0.1162, 0.7666],
         [0.8801, 0.4203, 0.8186, 0.0463],
         [0.7306, 0.2009, 0.3265, 0.6684]]])

In [127]:
#permute
b.permute(2,0,1).shape #2  wala 0 pe ,0wala 1 pe and 1 wala 2 pe

torch.Size([4, 2, 3])

In [129]:
#unsqueeze
#size od typical image
c=torch.rand(226,226,3)
c.unsqueeze(1).shape #us position pe naya tensor add kar do

torch.Size([226, 1, 226, 3])

In [131]:
#squeeze

d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

### Numpy and PyTorch

In [132]:
import numpy as np


In [134]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [135]:
b=a.numpy()

In [136]:
b

array([1, 2, 3])

In [137]:
type(b)

numpy.ndarray

In [138]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [139]:
torch.from_numpy(c)

tensor([1, 2, 3])